# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MemoriaDescriptiva
                                 A QGIS plugin
 Genera una memoria descriptiva en Word a partir de capas de puntos, líneas y polígonos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-29
        copyright            : (C) 2025 by Yuri Caller
        email                : yuricaller@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yuri Caller'
__date__ = '2025-11-29'
__copyright__ = '(C) 2025 by Yuri Caller'

import sys
import subprocess
import os

def instalar_dependencias():
    """
    Instala las dependencias necesarias para el plugin
    """
    try:
        import docx
        print("python-docx ya está instalado")
        return True
    except ImportError:
        print("python-docx no encontrado. Instalando...")
        
        try:
            # Obtener el ejecutable de Python de QGIS
            python_exe = sys.executable
            
            # Instalar python-docx
            subprocess.check_call([python_exe, "-m", "pip", "install", "python-docx"])
            
            print("python-docx instalado correctamente")
            return True
            
        except Exception as e:
            print(f"Error al instalar python-docx: {e}")
            return False

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MemoriaDescriptiva class from file MemoriaDescriptiva.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Intentar instalar dependencias antes de cargar el plugin
    if not instalar_dependencias():
        from qgis.PyQt.QtWidgets import QMessageBox
        QMessageBox.warning(
            None,
            "Memoria Descriptiva - Error de Dependencias",
            "No se pudo instalar python-docx automáticamente.\n\n"
            "Por favor, instálelo manualmente:\n"
            "1. Abra OSGeo4W Shell (o símbolo del sistema)\n"
            "2. Ejecute: python -m pip install python-docx\n"
            "3. Reinicie QGIS"
        )
    
    from .memoria_descriptiva import MemoriaDescriptivaPlugin
    return MemoriaDescriptivaPlugin(iface)